vocab = {
    "notebook": "тетрадь",
    "cranberry": "клюква",
    "parrot": "попугай",
    "I use to it": "Я привык к этому",
    "mug": "кружка",
    "glass": "стакан",
    "charger": "зарядное устройство",
    "cup": "чашка",
    "short glass/stemware": "рюмка",
    "workout": "тренировка",
    "shorts": "шорты",
    "sneakers": "кроссовки",
    "diary": "дневник / ежедневник",
    "scissors": "ножницы",
    "tissue": "ткань",
    "bag": "сумка",
    "backpack": "рюкзак",
    "laptop": "ноутбук",
    "umbrella": "зонт",
    "hand": "рука",
    "sunglasses": "солнцезащитные очки",
    "purse": "маленький кошелек для мелочи",
    "monday": "понедельник",
    "tuesday": "вторник",
    "wednesday": "среда",
    "thursday": "четверг",
    "friday": "пятница",
    "saturday": "суббота",
    "sunday": "воскресенье",
    "weekend": "выходные",
    "weekday": "будний день",
    "see you": "увидимся",
    "a thousand": "тысяча",
    "I want": "Я хочу",
    "favour": "одолжение",
    "other": "другой",
    "differences": "различия",
    "especially": "особенно",
    "vice versa": "наоборот",
    "you're welcome": "пожалуйста",
    "pronunciation": "произношение",
    "vocabulary": "словарный запас",
    "spelling": "правописание",
    "before": "до",
    "after": "после",
    "often": "часто",
    "always": "всегда",
    "usually": "обычно",
    "never": "никогда",
    "rarely": "редко",
    "sometimes": "иногда",
    "once a week": "1 раз в неделю",
    "twice a week": "2 раза в неделю",
    "three times a week": "3 раза в неделю",
    "beautiful": "красивый",
    "big": "большой",
    "cheap": "дешевый",
    "clean": "чистый",
    "easy": "легкий",
    "fast": "быстрый",
    "full": "полный",
    "good": "хороший",
    "high": "высокий",
    "hot": "жарко",
    "light": "светлый",
    "long": "длинный",
    "old": "старый",
    "rich": "богатый",
    "right": "верный",
    "safe": "безопасный",
    "same": "одинаковый",
    "strong": "сильный",
    "tall": "высокий",
    "necessary": "необходимый",
    "place": "место",
    "sentence": "предложение",
    "noun": "существительное",
    "vowel": "гласные",
    "make": "сделать",
    "adjective": "прилагательное",
    "the same": "то же самое",
    "exercise": "упражнение",
    "I'm going for it": "Я иду к этому",
    "feel": "чувствовать",
    "guess": "угадать",
    "further": "далее",
    "look": "смотреть",
    "look at": "смотреть на",
    "look for": "искать",
    "look after": "ухаживать/присматривать",
    "worried": "волнуется",
    "happy": "счастливый",
    "thirsty": "жажда",
    "angry": "злой",
    "hungry": "голодный",
    "tired": "уставший",
    "stressed": "напряженный",
    "sad": "грустно",
    "bored": "скучный",
    "frightened": "напуганный",
    "take": "брать",
    "wear": "носить",
    "flat": "квартира",
    "study": "учиться",
    "turn off": "выключить",
    "change": "изменить",
    "sweetheart": "возлюбленная",
    "darling": "дорогая",
    "freedom": "свобода",
    "awful": "ужасный",
    "scenery": "пейзаж",
    "What's the matter?": "Что случилось?",
    "near": "рядом с",
    "question": "вопрос",
    "see": "видеть",
    "watch": "присматривать",
    "drop": "падать",
    "happen": "случаться / происходить",
    "ask": "спрашивать / просить",
    "invite": "приглашать",
    "as": "в качестве",
    "like": "например",
    "What do you do?": "Чем вы занимаетесь?",
    "What about you": "Что насчет вас?",
    "really": "действительно",
    "me too": "я тоже",
    "who": "кто",
    "what": "что",
    "where": "где",
    "when": "когда",
    "whose": "чей",
    "whom": "кого",
    "how": "как / насколько",
    "how much / how many": "сколько",
    "how long": "как долго",
    "how often": "как часто",
    "how old": "сколько лет",
    "general": "главный / общий",
    "highlighted": "выделено",
    "hardly ever": "почти никогда",
    "vet": "ветеринар",
    "factory": "завод",
    "which": "какой",
    "why": "почему",
    "prefer": "предпочтение",
    "what kind of": "какой",
    "tidy": "аккуратный",
    "article": "статья",
    "founder": "основатель",
    "married": "женат",
    "follow": "следовать",
    "advantage": "преимущество",
    "meet": "встречать",
    "jelaous": "желанный",
    "inside": "изнутри",
    "outside": "снаружи",
    "late": "поздний",
    "swimming pool": "бассейн",
    "It’s five past three": "5 минут 4-го",
    "It’s a quarter past six": "четверть седьмого",
    "It’s half past seven": "половина восьмого",
    "It’s tventy to ten": "20 минут до 10",
    "It’s eleven o’clock": "11 ровно",
    "spend": "тратить",
    "enjoy": "наслаждаться",
    "miss": "скучать",
    "spend time": "проводить время",
    "law": "закон",
    "dayly": "ежедневный",
    "boring": "скучно",
    "afternoon": "после обеда",
    "evening": "вечер",
    "occasionally": "периодически",
    "healthy": "здоровый",
    "lamb": "мясо ягненка",
    "beans": "бобы",
    "peas": "горох",
    "main orders": "основные блюда",
    "side orders": "гарниры/дополнительные блюда",
    "waiter / waitress": "официант/официантка",
    "Do you have ...": "У вас есть ...?",
    "Can I have a ...": "Можно мне ...?",
    "I would like to": "Я буду",
    "I'll have": "Я возьму/закажу",
    "fries": "картофель фри",
    "What would you recommend?": "Что вы можете порекомендовать?",
    "do exercise": "делать зарядку",
    "band": "музыкальная группа",
    "during": "в течении",
    "at the background": "на заднем плане",
    "competitions": "соревнования",
    "buy": "покупать",
    "call": "звонить",
    "dance": "танцевать",
    "at all": "совсем",
    "somebody/something": "кто-то/что-то",
    "anybody/anything": "кто-нибудь/что-нибудь",
    "look forward to": "жду с нетерпением",
    "draw": "рисовать",
    "find": "найти",
    "forget": "забыть",
    "give": "дать/дарить",
    "hear": "слышать",
    "help": "помогать",
    "leave": "покидать",
    "paint": "красить",
    "remember": "помнить",
    "run": "бегать",
    "send": "отправлять",
    "sing": "петь",
    "swim": "плавать",
    "talk": "разговаривать",
    "tell": "сказать",
    "try": "пробовать",
    "use": "использовать",
    "wait for": "ждать",
    "connected to": "связанный",
    "in the childhood": "в детстве",
    "preparation": "подготовка",
    "couple": "пара",
    "uncle": "дядя",
    "aunt": "тётя",
    "husband": "муж",
    "cousin": "двоюродный брат/сестра",
    "nephew": "племянник",
    "niece": "племянница",
    "originally": "первоначально",
    "cardiac surgery": "кардиохирургия",
    "describe": "описывать",
    "your": "твой",
    "between": "между",
    "get": "получить",
    "break": "перерыв",
    "desk": "рабочий стол",
    "lectures": "лекции",
    "research": "исследовать",
    "probably": "возможно",
    "think": "думать",
    "about": "о",
    "values": "ценности",
    "example": "пример",
    "is away": "находится в отъезде",
    "reason": "причина",
    "hairdress": "причёска",
    "there": "там",
    "lot": "много",
    "turn": "очередь",
    "papers": "документы",
    "repair": "ремонт",
    "choose": "выбирать",
    "again": "снова",
    "answer": "ответ",
    "ugly": "страшный",
    "small": "маленький",
    "expensive": "дорогой",
    "dirty": "грязный",
    "difficult": "сложный",
    "slow": "медленный",
    "empty": "пустой",
    "bad": "плохой",
    "low": "низкий",
    "cold": "холодный",
    "dark": "темный",
    "short": "низкий",
    "new": "новый",
    "young": "молодой",
    "poor": "бедный",
    "left": "левый",
    "wrong": "не верный",
    "dangerous": "опасный",
    "different": "разный",
    "weak": "слабый",
    "terrible": "ужасный",
    "shave": "брить",
    "midnight": "полночь",
    "need": "необходимость"
}
